# GENERATED FILE - DO NOT EDIT BY HAND.
#
# Regenerate with:
#   python3 tools/gen_schema.py <java-src-root>
#
# Source tree : /Users/seand/development/openrealm/src
# Generated   : 2026-09-23 19:59:49Z
# Packets     : 47
# Entities    : 20
#
# Field tuples are [name, wire_type, is_collection]; list order is wire order.
# Primitive wire types are byte, bool, short, int, long, float and string;
# anything else names an entry in ENTITIES.
#
# A tuple of [name, "mask", false, sections] is a masked-section block: one
# mask byte, then the fields of each section whose bit is set, in order.
# sections is [[bit, [field tuples]], ...].
class_name NetSchema

const SOURCE_TREE := "/Users/seand/development/openrealm/src"

# packet id -> class name
const PACKET_NAMES := {
	1: "PlayerMovePacket",
	2: "UpdatePacket",
	3: "ObjectMovePacket",
	4: "TextPacket",
	5: "HeartbeatPacket",
	6: "PlayerShootPacket",
	7: "CommandPacket",
	8: "LoadMapPacket",
	9: "LoadPacket",
	10: "UnloadPacket",
	11: "UseAbilityPacket",
	12: "MoveItemPacket",
	13: "UsePortalPacket",
	14: "TextEffectPacket",
	15: "PlayerDeathPacket",
	16: "RequestTradePacket",
	17: "AcceptTradeRequestPacket",
	18: "UpdatePlayerTradeSelectionPacket",
	19: "UpdateTradePacket",
	20: "DeathAckPacket",
	21: "CreateEffectPacket",
	22: "LoginAckPacket",
	23: "GlobalPlayerPositionPacket",
	24: "PlayerStatePacket",
	25: "CompactMovePacket",
	26: "PlayerPosAckPacket",
	27: "ConsumeShardStackPacket",
	28: "InteractTilePacket",
	29: "OpenForgePacket",
	30: "ForgeEnchantPacket",
	31: "ForgeDisenchantPacket",
	32: "OpenFameStorePacket",
	33: "BuyFameItemPacket",
	34: "OpenItemStorePacket",
	35: "ItemStoreUpdatePacket",
	36: "ItemStoreMovePacket",
	37: "SplitStackPacket",
	38: "AbilityCastStartPacket",
	39: "HotbarSwapPacket",
	40: "InvestSkillPointPacket",
	41: "PartyUpdatePacket",
	42: "RealmPurificationPacket",
	43: "SkillsPacket",
	44: "OpenExchangeMarketPacket",
	45: "ExchangeItemsPacket",
	46: "QuestStatePacket",
	101: "TestPacket",
}

# class name -> packet id
const PACKET_IDS := {
	"AbilityCastStartPacket": 38,
	"AcceptTradeRequestPacket": 17,
	"BuyFameItemPacket": 33,
	"CommandPacket": 7,
	"CompactMovePacket": 25,
	"ConsumeShardStackPacket": 27,
	"CreateEffectPacket": 21,
	"DeathAckPacket": 20,
	"ExchangeItemsPacket": 45,
	"ForgeDisenchantPacket": 31,
	"ForgeEnchantPacket": 30,
	"GlobalPlayerPositionPacket": 23,
	"HeartbeatPacket": 5,
	"HotbarSwapPacket": 39,
	"InteractTilePacket": 28,
	"InvestSkillPointPacket": 40,
	"ItemStoreMovePacket": 36,
	"ItemStoreUpdatePacket": 35,
	"LoadMapPacket": 8,
	"LoadPacket": 9,
	"LoginAckPacket": 22,
	"MoveItemPacket": 12,
	"ObjectMovePacket": 3,
	"OpenExchangeMarketPacket": 44,
	"OpenFameStorePacket": 32,
	"OpenForgePacket": 29,
	"OpenItemStorePacket": 34,
	"PartyUpdatePacket": 41,
	"PlayerDeathPacket": 15,
	"PlayerMovePacket": 1,
	"PlayerPosAckPacket": 26,
	"PlayerShootPacket": 6,
	"PlayerStatePacket": 24,
	"QuestStatePacket": 46,
	"RealmPurificationPacket": 42,
	"RequestTradePacket": 16,
	"SkillsPacket": 43,
	"SplitStackPacket": 37,
	"TestPacket": 101,
	"TextEffectPacket": 14,
	"TextPacket": 4,
	"UnloadPacket": 10,
	"UpdatePacket": 2,
	"UpdatePlayerTradeSelectionPacket": 18,
	"UpdateTradePacket": 19,
	"UseAbilityPacket": 11,
	"UsePortalPacket": 13,
}

# packet class name -> ordered field list
const PACKETS := {
	"AbilityCastStartPacket": [
		["playerId", "long", false],
		["abilityId", "int", false],
		["slot", "byte", false],
		["durationMs", "int", false],
		["worldTargetX", "float", false],
		["worldTargetY", "float", false],
	],
	"AcceptTradeRequestPacket": [
		["accepted", "bool", false],
		["player0", "NetPlayer", false],
		["player1", "NetPlayer", false],
		["player0Inv", "NetGameItem", true],
		["player1Inv", "NetGameItem", true],
	],
	"BuyFameItemPacket": [
		["itemId", "int", false],
	],
	"CommandPacket": [
		["playerId", "long", false],
		["commandId", "byte", false],
		["command", "string", false],
	],
	"CompactMovePacket": [
		["movements", "NetCompactMovement", true],
	],
	"ConsumeShardStackPacket": [
		["fromSlotIndex", "byte", false],
	],
	"CreateEffectPacket": [
		["effectType", "short", false],
		["posX", "float", false],
		["posY", "float", false],
		["radius", "float", false],
		["duration", "short", false],
		["targetPosX", "float", false],
		["targetPosY", "float", false],
		["tier", "byte", false],
		["ownerId", "long", false],
	],
	"DeathAckPacket": [
	],
	"ExchangeItemsPacket": [
		["sourceItemId", "int", false],
		["targetItemId", "int", false],
		["quantity", "int", false],
	],
	"ForgeDisenchantPacket": [
		["targetItemSlot", "byte", false],
	],
	"ForgeEnchantPacket": [
		["targetItemSlot", "byte", false],
		["crystalItemId", "int", false],
		["crystalSlotIndex", "byte", false],
		["essenceSlotIndex", "byte", false],
		["pixelX", "byte", false],
		["pixelY", "byte", false],
	],
	"GlobalPlayerPositionPacket": [
		["players", "NetPlayerPosition", true],
	],
	"HeartbeatPacket": [
		["timestamp", "long", false],
	],
	"HotbarSwapPacket": [
		["slot", "byte", false],
		["direction", "byte", false],
	],
	"InteractTilePacket": [
		["tileX", "int", false],
		["tileY", "int", false],
	],
	"InvestSkillPointPacket": [
		["slot", "byte", false],
	],
	"ItemStoreMovePacket": [
		["storeKind", "byte", false],
		["fromSide", "byte", false],
		["fromIdx", "int", false],
		["toSide", "byte", false],
		["toIdx", "int", false],
	],
	"ItemStoreUpdatePacket": [
		["storeKind", "byte", false],
		["playerId", "long", false],
		["items", "NetGameItem", true],
	],
	"LoadMapPacket": [
		["realmId", "long", false],
		["mapId", "short", false],
		["dungeonId", "short", false],
		["mapWidth", "short", false],
		["mapHeight", "short", false],
		["tiles", "NetTile", true],
	],
	"LoadPacket": [
		["players", "NetPlayer", true],
		["enemies", "NetEnemy", true],
		["bullets", "NetBullet", true],
		["containers", "NetLootContainer", true],
		["portals", "NetPortal", true],
		["difficulty", "byte", false],
	],
	"LoginAckPacket": [
	],
	"MoveItemPacket": [
		["targetSlotIndex", "byte", false],
		["fromSlotIndex", "byte", false],
		["drop", "bool", false],
		["consume", "bool", false],
	],
	"ObjectMovePacket": [
		["movements", "NetObjectMovement", true],
	],
	"OpenExchangeMarketPacket": [
		["playerId", "long", false],
	],
	"OpenFameStorePacket": [
		["playerId", "long", false],
		["accountFame", "long", false],
	],
	"OpenForgePacket": [
		["playerId", "long", false],
	],
	"OpenItemStorePacket": [
		["storeKind", "byte", false],
		["playerId", "long", false],
		["items", "NetGameItem", true],
	],
	"PartyUpdatePacket": [
		["partyId", "long", false],
		["members", "NetPartyMember", true],
		["leaderId", "long", false],
	],
	"PlayerDeathPacket": [
		["playerId", "long", false],
	],
	"PlayerMovePacket": [
		["seq", "int", false],
		["vx", "float", false],
		["vy", "float", false],
	],
	"PlayerPosAckPacket": [
		["seq", "int", false],
		["posX", "float", false],
		["posY", "float", false],
	],
	"PlayerShootPacket": [
		["projectileId", "long", false],
		["projectileGroupId", "int", false],
		["destX", "float", false],
		["destY", "float", false],
		["srcX", "float", false],
		["srcY", "float", false],
	],
	"PlayerStatePacket": [
		["playerId", "long", false],
		["health", "int", false],
		["mana", "int", false],
		["effectIds", "short", true],
		["effectTimes", "long", true],
		["effectStacks", "short", true],
	],
	"QuestStatePacket": [
		["playerId", "long", false],
		["stars", "long", false],
		["json", "string", false],
	],
	"RealmPurificationPacket": [
		["realmId", "long", false],
		["progress", "long", false],
		["goal", "long", false],
		["difficulty", "float", false],
		["tier", "int", false],
		["modifiers", "string", false],
	],
	"RequestTradePacket": [
		["requestingPlayerName", "string", false],
	],
	"SkillsPacket": [
		["playerId", "long", false],
		["xp0", "long", false],
		["xp1", "long", false],
		["xp2", "long", false],
		["xp3", "long", false],
		["xp4", "long", false],
		["xp5", "long", false],
		["xp6", "long", false],
		["xp7", "long", false],
		["xp8", "long", false],
	],
	"SplitStackPacket": [
		["fromSlot", "int", false],
	],
	"TestPacket": [
		["test0", "string", false],
		["test1", "string", false],
		["test2", "long", false],
		["test3", "short", false],
		["test4", "bool", true],
	],
	"TextEffectPacket": [
		["textEffectId", "byte", false],
		["entityType", "byte", false],
		["targetEntityId", "long", false],
		["text", "string", false],
		["posX", "float", false],
		["posY", "float", false],
	],
	"TextPacket": [
		["from", "string", false],
		["to", "string", false],
		["message", "string", false],
	],
	"UnloadPacket": [
		["players", "long", true],
		["bullets", "long", true],
		["enemies", "long", true],
		["containers", "long", true],
		["portals", "long", true],
	],
	"UpdatePacket": [
		["playerId", "long", false],
		["playerName", "string", false],
		["stats", "NetStats", false],
		["health", "int", false],
		["mana", "int", false],
		["experience", "long", false],
		["inventory", "NetGameItem", true],
		["hpPotions", "byte", false],
		["mpPotions", "byte", false],
		["dyeId", "int", false],
		["availableSkillPoints", "int", false],
		["investedSlot0", "byte", false],
		["investedSlot1", "byte", false],
		["investedSlot2", "byte", false],
		["investedSlot3", "byte", false],
		["stars", "int", false],
	],
	"UpdatePlayerTradeSelectionPacket": [
		["selection", "NetInventorySelection", false],
	],
	"UpdateTradePacket": [
		["selections", "NetTradeSelection", false],
	],
	"UseAbilityPacket": [
		["posX", "float", false],
		["posY", "float", false],
		["abilityIndex", "byte", false],
	],
	"UsePortalPacket": [
		["portalId", "long", false],
		["fromRealmId", "long", false],
		["toVault", "byte", false],
		["toNexus", "byte", false],
	],
}

# nested wire-entity class name -> ordered field list
const ENTITIES := {
	"NetAttributeModifier": [
		["statId", "byte", false],
		["deltaValue", "byte", false],
	],
	"NetBullet": [
		["id", "long", false],
		["projectileId", "int", false],
		["size", "short", false],
		["pos", "Vector2f", false],
		["dX", "float", false],
		["dY", "float", false],
		["angle", "float", false],
		["magnitude", "float", false],
		["range", "float", false],
		["damage", "short", false],
		["length", "short", false],
		["lifetimeTicks", "int", false],
		["srcEntityId", "long", false],
		["createdTime", "long", false],
		["flags", "short", true],
		["_mask", "mask", false, [
			[1, [
				["invert", "bool", false],
				["timeStep", "long", false],
				["amplitude", "short", false],
				["frequency", "short", false],
			]],
			[2, [
				["orbitCenterX", "float", false],
				["orbitCenterY", "float", false],
				["orbitRadius", "float", false],
				["orbitPhase", "float", false],
			]],
			[4, [
				["targetEntityId", "long", false],
			]],
			[8, [
				["overrideSpriteKey", "string", false],
				["overrideSpriteRow", "int", false],
				["overrideSpriteCol", "int", false],
				["overrideSpriteSize", "int", false],
				["overrideSpriteHeight", "int", false],
			]],
		]],
	],
	"NetCompactMovement": [
		["shortEntityId", "short", false],
		["posX", "float", false],
		["posY", "float", false],
		["velXFixed", "short", false],
		["velYFixed", "short", false],
		["flags", "byte", false],
	],
	"NetDamage": [
		["projectileGroupId", "int", false],
		["min", "short", false],
		["max", "short", false],
	],
	"NetEffect": [
		["self", "bool", false],
		["effectId", "short", false],
		["duration", "long", false],
		["cooldownDuration", "long", false],
		["mpCost", "short", false],
	],
	"NetEnchantment": [
		["statId", "byte", false],
		["deltaValue", "byte", false],
		["pixelX", "byte", false],
		["pixelY", "byte", false],
		["pixelColor", "int", false],
	],
	"NetEnemy": [
		["id", "long", false],
		["enemyId", "int", false],
		["weaponId", "int", false],
		["size", "short", false],
		["pos", "Vector2f", false],
		["dX", "float", false],
		["dY", "float", false],
		["difficulty", "float", false],
		["health", "int", false],
		["maxHealth", "int", false],
		["shortId", "short", false],
	],
	"NetGameItem": [
		["itemId", "int", false],
		["uid", "string", false],
		["name", "string", false],
		["description", "string", false],
		["stats", "NetStats", false],
		["damage", "NetDamage", false],
		["effect", "NetEffect", false],
		["consumable", "bool", false],
		["tier", "byte", false],
		["targetSlot", "byte", false],
		["targetClass", "byte", false],
		["fameBonus", "byte", false],
		["stackable", "bool", false],
		["maxStack", "int", false],
		["stackCount", "int", false],
		["category", "string", false],
		["forgeStatId", "byte", false],
		["forgeSlotId", "byte", false],
		["enchantments", "NetEnchantment", true],
		["rarity", "byte", false],
		["attributeModifiers", "NetAttributeModifier", true],
		["gemstoneType", "byte", false],
		["gemPixelX", "byte", false],
		["gemPixelY", "byte", false],
		["gemPixelColor", "int", false],
	],
	"NetGameItemRef": [
		["itemId", "int", false],
		["slotIdx", "int", false],
		["itemUuid", "string", false],
	],
	"NetInventorySelection": [
		["playerId", "long", false],
		["selection", "bool", true],
		["itemRefs", "NetGameItemRef", true],
		["confirmed", "bool", false],
	],
	"NetLootContainer": [
		["lootContainerId", "long", false],
		["uid", "string", false],
		["isChest", "bool", false],
		["tier", "byte", false],
		["items", "NetGameItem", true],
		["pos", "Vector2f", false],
		["spawnedTime", "long", false],
		["contentsChanged", "bool", false],
		["soulboundPlayerId", "long", false],
	],
	"NetObjectMovement": [
		["entityId", "long", false],
		["entityType", "byte", false],
		["posX", "float", false],
		["posY", "float", false],
		["velX", "float", false],
		["velY", "float", false],
		["flags", "byte", false],
	],
	"NetPartyMember": [
		["playerId", "long", false],
		["name", "string", false],
		["classId", "int", false],
		["health", "int", false],
		["maxHealth", "int", false],
		["mana", "int", false],
		["maxMana", "int", false],
		["level", "int", false],
		["realmId", "long", false],
		["effectIds", "short", true],
		["hotbarBindings", "int", true],
		["abilityCooldownEnds", "long", true],
		["hotbarInvested", "int", true],
		["stats", "NetStats", false],
		["equipment", "NetGameItem", true],
	],
	"NetPlayer": [
		["id", "long", false],
		["name", "string", false],
		["accountUuid", "string", false],
		["characterUuid", "string", false],
		["classId", "int", false],
		["size", "short", false],
		["pos", "Vector2f", false],
		["dX", "float", false],
		["dY", "float", false],
		["shortId", "short", false],
		["chatRole", "string", false],
		["dyeId", "int", false],
	],
	"NetPlayerPosition": [
		["playerId", "long", false],
		["name", "string", false],
		["x", "float", false],
		["y", "float", false],
		["teleportable", "bool", false],
	],
	"NetPortal": [
		["id", "long", false],
		["portalId", "short", false],
		["fromRealmId", "long", false],
		["toRealmId", "long", false],
		["expires", "long", false],
		["pos", "Vector2f", false],
		["targetLabel", "string", false],
		["targetDifficulty", "float", false],
		["targetPlayerCount", "int", false],
		["targetPurificationProgress", "long", false],
		["targetPurificationGoal", "long", false],
		["targetTier", "int", false],
		["targetModifiers", "string", false],
	],
	"NetStats": [
		["hp", "int", false],
		["mp", "short", false],
		["def", "short", false],
		["str", "short", false],
		["spd", "short", false],
		["dex", "short", false],
		["vit", "short", false],
		["wis", "short", false],
	],
	"NetTile": [
		["tileId", "short", false],
		["layer", "byte", false],
		["xIndex", "int", false],
		["yIndex", "int", false],
	],
	"NetTradeSelection": [
		["player0Selection", "NetInventorySelection", false],
		["player1Selection", "NetInventorySelection", false],
	],
	"Vector2f": [
		["x", "float", false],
		["y", "float", false],
	],
}

static func fields_for(type_name: String) -> Array:
	if PACKETS.has(type_name):
		return PACKETS[type_name]
	if ENTITIES.has(type_name):
		return ENTITIES[type_name]
	return []

static func is_known(type_name: String) -> bool:
	return PACKETS.has(type_name) or ENTITIES.has(type_name)
